### ISSUE TITLE
1.16 / 1.17 Research tasks

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#14324]
### Todo

* [ ] Anything?

Feel free to add to this team. 

#### completed in #14356
* [x] How many users use light/dark/system theme?
* [x] How many users use non-builtin themes?
* [x] Number of themes a user has?
* [x] Number of `sendInput` actions the user has defined
* [x] Number of terminal instances where we get a CWD shell integration sequence
* [x] Number of terminal instances where we get mark sequences
* [x] Number of users with automarkPrompts enabled for at least one profile

**Comment by zadjii-msft** [comment]
Oh look, we didn't add anything else. Cool, let's close this one.
