### ISSUE TITLE
Finish the SSH profile generator

### ISSUE THREAD

**Issue by McLavish** [microsoft/terminal#15007]
_maintainer note: hijacking OP to put tasks in here_

Originally tracked in #9031
Added in #14042

```[tasklist]
### Tasks
- [ ] https://github.com/MicrosoftDocs/terminal/issues/641
- [ ] Fix issues that @DHowett found in the parser
- [ ] Something about making the SUI UX easier to use, disable?
```

<hr>

### Windows Terminal version

1.17.1023

### Windows build number

10.0.22621.1413

### Other Software

OpenSSH_for_Windows_8.6p1
LibreSSL 3.4.3

### Steps to reproduce

1. Install Windows Terminal (Preview) through the Microsoft Store
2. Install the OpenSSH client from Windows Optional Features
3. Create a user OpenSSH config file under %userprofile%\.ssh\config:
```
Host myhost  
    HostName something.domain.com  
    User myuser  
    IdentityFile "C:\Users\myuser\myfolder\id_rsa"
```
5. (Optional) Add "disabledProfileSources" : [ ], to settings.json
6. Open Windows Terminal (Preview)

Note: It appears adding "disabledProfileSources" : [ "Windows.Terminal.SSH" ], produces a Value not accepted warning in VsCode as it's not listed in the profiles schema ![DynamicProfileSource](https://github.com/microsoft/terminal/blob/main/doc/cascadia/profiles.schema.json) enum.
![bug](https://user-images.githubusercontent.com/32342099/225904232-c1d4db80-0b7e-45f1-b88b-e6c75e1cf2bf.png)

### Expected Behavior

Docs says that "Windows Terminal version 1.XX+ can dynamically generate profiles to connect to the SSH hosts within your OpenSSH config file"

### Actual Behavior

Nothing happens

**Comment by elsaco** [comment]
@McLavish the feature might not be enabled, yet. See details at;

https://github.com/microsoft/terminal/blob/b9248fa903eaa8d187c72bf08f8aa17b25f9d6bb/src/features.xml#L141-L146

You could enable it using a branding token and build the terminal. I use `dev` token and it does generate an SSH profile:

 
![wt_ssh_profile](https://user-images.githubusercontent.com/3933920/226074025-26166595-9531-4aed-ad09-9ffe52aa01de.png)

To my surprise clicking on that profile opened a SSH connection to a Pi4 box, no errors!

**Comment by McLavish** [comment]
@elsaco I guess you're right but then it shouldn't be listed as a feature in the [windows terminal docs](https://learn.microsoft.com/en-us/windows/terminal/tutorials/ssh)

![image](https://user-images.githubusercontent.com/32342099/226124041-b3f9ca3f-2489-4ff1-8157-17cb6e585fab.png)

**Comment by nguyen-dows** [comment]
@McLavish You are correct. There is already been an issue made to get this removed from the docs page: https://github.com/MicrosoftDocs/terminal/issues/641

**Comment by zadjii-msft** [comment]
You know what, good callout. We should remove this from the docs until we ship this. Clearly our docs need some love 😅 

I'm gonna hijack your OP to track the rest of the work needed to get this across the finish line.

**Comment by rmdes** [comment]
Any chance this is working now ?
