### ISSUE TITLE
Suggestions UI ship list

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#15845]
```[tasklist]
### Tasks
- [ ] Accessibility tags all have `CommandPalette_` strings 🤣 
- [ ] useCommandline should leave the cursor at the _end_ of the input, not at the start
- [ ] useCommandline, when bottom-up, should leave the _last_ list item selected, not the first. 
- [ ] ^ Probably applies to any changes to the filter text when bottom up.
```

**Comment by DHowett** [comment]
@zadjii-msft can you punt the 1.21 and 1.22 things to the appropriate milestone and move this issue out?
