### ISSUE TITLE
Epic: Fix remaining issues with non-client drawing

### ISSUE THREAD

**Issue by DHowett-MSFT** [microsoft/terminal#1625]
Misc. Window Management bucket
* [ ] Make sure caption controls "dim out" when window loses NC focus (`WM_NCACTIVATE`?)
* [x] #1840 When we're maximized, the system thinks we're a full-screen app. We need to jiggle the window by 1px or something.

Others:
* [ ] #2001 Make sure MinMaxCloseControl supports FullScreen & Tablet Mode
* [x] #2100 When a dialog is open, the titlebar is the wrong color
  - [x] Also: #4744 Investigate Acrylic in titlebar / not using a `HRGN` for the titlebar 
* [ ] #1230 I have to restart the new terminal to see the effects of changing between light and dark windows theme.
* [x] #2541 When the window is maximized, there should be no padding above the tabs
* [x] #3440 Windows Terminal does not open with button displaying "maximized" state 
* [x] #4288 Maximize and minimize window buttons incorrect rendering 
* [x] strange bar appear while maximized #8384 

<details>
<summary>Fixed in `master`</summary>

* [x] Suspicious remains of previous window borders flash up when closing the window (#3222) (PR#3394)
* [x] White border at the bottom of the window. (#3064) (PR #3394)
* [x] Stop creating and throwing away so many `HRGN`s during move-size. (PR #3394)
* [x] #3136 we learned that `CXDRAG` and `CYDRAG` are not the right things to use; use the right things. (PR #3394)
* [x] #1307 Thick border around window, and drag handles should _not_ be only over that border. (PR #3394)
* [x] #1897 There's a bunch of duplicated work, well, everywhere. (PR #3394)
* [x] make the window border have distinct edges (right now it blends in with white/black things); consider the user's accent color somehow?
   - Could this be solved just by not `NCPAINT`ing, and letting DWM draw our window shadow again?

Possibly related:
* [x] #1859 The border width should match the value from the system theme
</details>
<details>
<summary>Fixed in &lt;0.6</summary>

* [x] Switch from `_` `-` `X` to real or real-looking caption controls

Definitely related, because we're handling `WM_NCPAINT`:
* [x] [huge bucket] look at getting the window shadow back (PR #1898)
* [x] make the window border less round on top (PR #1898)

Maybe related:
* [x] make the window border less painfully black/white

Misc. Window Management bucket
* [x] _consider_ giving NonClientIslandWindow knowledge about its caption button box for a more direct connection (PR #1948)
* [x] #1780 Double clicking on the drag bar to maximize does not update the maximize button icon 
* [x] Make sure maximize button maintains correct state when window is maximized in any manner
* [x] #1055 Window edges are cut off when the window is maximized on a secondary display (PR #1921)
* [x] #2028 Clicking on the TitleBar does not close the dropdown menu
* [x] #2268 Maximizing terminal when window is across two monitors causes bars to bleed across monitor.

Others:
* [x] #1913 Dark Theme requires settings reload (PR #2107)
</details>

**Comment by DHowett-MSFT** [comment]
We need to handle the window message for theme change probably.

**Comment by zadjii-msft** [comment]
Closing this one out since #2001 is really the only thing left in it.
