### ISSUE TITLE
Maingocanhiu00

### ISSUE THREAD

**Issue by maingocanh00** [microsoft/terminal#16469]
### Windows Terminal version

[Environment]::OSVersion

### Windows build number

[Environment]::OSVersion

### Other Software

[Environment]::OSVersion

### Steps to reproduce

[Environment]::OSVersion

### Expected Behavior

[Environment]::OSVersionKIRJF21700038   

### Actual Behavior

KIRJF21700038  [Environment]::OSVersionKIRJF21700038   
```[tasklist]
### Tasks
- [ ] https://github.com/microsoft/terminal/issues/1472
- [ ] https://github.com/microsoft/terminal/issues/14881
- [ ] https://github.com/microsoft/terminal/issues/11071
```

```[tasklist]
### Tasks
```
