### ISSUE TITLE
[1.21] Clicking on the right side of a combobox doesn't cause it to open / dropdown

### ISSUE THREAD

**Issue by Zeroes1** [microsoft/terminal#17062]
### Windows Terminal version

1.21.1011.0

### Windows build number

10.0.19045.3448

### Steps to reproduce

look the video
https://github.com/microsoft/terminal/assets/11919060/f5c52bf2-d51c-482c-9dfc-557d919ec554

ps. for future is good idea post issue like BUG for CANARY builds WT?

### Expected Behavior

good work wit combobox 
latest good canary buid:  terminal-1.21.931.0

### Actual Behavior

terminal-1.21.991.0
terminal-1.21.1011.0
is bad for work with combobox

**Comment by zadjii-msft** [comment]
> for future is good idea post issue like BUG for CANARY builds WT

Yes absolutely! If you're using canary and find bugs in it, absolutely file them here 😄 

----

21.931 included the font face combo box, so that wasn't the source of this regression.

**Comment by DHowett** [comment]
Here are the commits for that version range:

```
1.21.991.0 (bad ) -> * b90eb93d2 Localization Updates - main - 04/06/2024 03:04:16 (#17025)
                     * 156b9aeea Make marks a stable feature (#16938)
                     * c3f44f773 Rewrite how marks are stored & add reflow (#16937)
                     * dc4026d18 Add support for restoring non-terminal panes, and opening them with `splitPane`, `newTab` (#16914)
                     * c063d2bad Change default pane keybindings to duplicate, rather than use default profile (#16951)
                     * 6a69b94fc Increase usage of fmt and FMT_COMPILE (#17012)
                     * 8d6e7a8a7 Buffer Restore: Fix serializing >32KiB (#17022)
                     * 1a6ba43dd Get rid of UpdateTerminalSettings (#17009)
                     * 67ae9f6c3 Refactor the SettingsTab to be a pane (#16172)
1.21.931.0 (good) -> * 2bcbe6b49 ci/rel: publish symbols using the internal symbol request API instead (#16991)
```

**Comment by DHowett** [comment]
@zadjii-msft 67ae9f6c3 - you may be the killer

**Comment by zadjii-msft** [comment]
You know, this is pretty dang painful. Promoting to blocking to investigate


Notes:

* [ ] ❌ b90eb93d2 Localization Updates - main - 04/06/2024 03:04:16 (#17025)
* [ ] ❔ 156b9aeea Make marks a stable feature (#16938)
* [ ] ❔ c3f44f773 Rewrite how marks are stored & add reflow (#16937)
* [ ] ❔ dc4026d18 Add support for restoring non-terminal panes, and opening them with `splitPane`, `newTab` (#16914)
* [ ] ❔ c063d2bad Change default pane keybindings to duplicate, rather than use default profile (#16951)
* [ ] 🏗️ 6a69b94fc Increase usage of fmt and FMT_COMPILE (#17012)
* [ ] ❔ 8d6e7a8a7 Buffer Restore: Fix serializing >32KiB (#17022)
* [ ] ❔ 1a6ba43dd Get rid of UpdateTerminalSettings (#17009)
* [ ] ❔ 67ae9f6c3 Refactor the SettingsTab to be a pane (#16172)
  - 👀
* [ ] ✅ 2bcbe6b49 ci/rel: publish symbols using the internal symbol request API instead (#16991)

**Comment by zadjii-msft** [comment]
![48ed8be3-eafd-4cf4-9969-cdb317837a95](https://github.com/microsoft/terminal/assets/18356694/7985a3cd-44de-4a4a-a106-cc75c0ac5a45)

* On the non-retemplated ones, it's just the arrow region that doesn't open it. 
* On the retemplated ones, it's anything except the label that doesn't open it
