### ISSUE TITLE
Feature Request: Make it easier for others to reuse Terminal code for Win7

### ISSUE THREAD

**Issue by WSLUser** [microsoft/terminal#2077]
# Summary of the new feature/enhancement
Make it easier to create a terminal similar to Windows Terminal that capable of running on Windows 7.

# A clear and concise description of what the problem is that the new feature would solve.

Provide a better terminal experience for organizations that still utilize Windows 7.

# Proposed technical implementation details (optional)

Missing features:

 * [ ]  You'll need conpty to be able to serve as the console API server on windows 7. You'd have to take the conhost.exe and bring it with you to be able to run on Windows 7.  Dependent on the next item:
 * [ ]  Conhost.exe was changed for Windows 8 to use condrv to handle console API calls, instead of _whatever it was using before_. So if you want to run conhost on Windows 7, you'll need to update it to be able to handle the windows 7 style connection. - Help wanted
 * [ ]  You'll need XAML Islands ported to windows 7 to be able to host our UI - XAML Islands can be used in WPF. See this [blog post](https://blogs.windows.com/windowsdeveloper/2018/11/02/xaml-islands-a-deep-dive-part-1/).
 * [x]  Need appx infrastructure to be able to install the .msix on Windows 7. Msix packaging supports Win7.
* [ ]  Need SxS WinRT activation downlevel to be able to support running 
the terminal as administrator. WPF can be used for this instead.
 
Probably more. Add to the list as needed.

**Comment by WSLUser** [comment]
https://github.com/microsoft/terminal/pull/1263 and https://github.com/microsoft/terminal/pull/1274 started this process for rendering. 

https://github.com/microsoft/terminal/pull/2004 starts the process of getting WPF controls implemented.

**Comment by miniksa** [comment]
We are not intending to take on the burden of supporting Windows 7 inside this new codebase. 

@bitcrazed will be preparing full details on our justification and reasoning behind this decision in an upcoming blog post.
