### ISSUE TITLE
Scenario: Add Support for UI Automation

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#4533]
# Megathread for v1.0 Accessibility Features

## Navigation
This is a subset of issues that are mainly located in the XAML Layer.
- [x] #2099: Automation Properties
- [x] #2142: Localization
- [x] #2102: Manage focus properly

## Providers
This is a subset of issues that are dedicated to presenting information from the Terminal to UIA Clients.
- [X] #634: Set-up UIA Tree
- [X] #1992: Create `IUiaData` (Terminal data needed for UIA)
- [X] #3161: Word Navigation
- [X] #2103: BoundingRect scaling
- [x] #2361: Scrolling
- [x] #4509: Box Selection
- [x] #1354: Wide Glyph Detection

## Signaling
This is a subset of issues that are dedicated to telling UIA Clients that our content has changed and needs to be re-read.
- [X] #2447: Selection
- [x] #2447: Output
- [x] #2447: Scrolling

## Miscellaneous Bugs and Polish
- [X] #2907: Crash when UIA Client is open
- [X] #2160, #3976: Navigation stuck
- [X] #3895, #1993: Refactor `UiaTextRange`
- [X] #4485: Word Navigation Hangs
- [x] #2551: BoundingRect scaling on High DPI
- [x] #1914 : Tracing
- [x] #4452: `ScreenInfoUiaProvider::GetSelection()`
- [x] #4507: `ScreenInfoUiaProvider::GetVisibleRanges()`
- [ ] #4421: Additional `UiaTextRange` Testing

**Comment by DHowett-MSFT** [comment]
This is a scenario that's tracking open issues, so I'm triaging it. Carlos already marked it v1.

**Comment by codeofdusk** [comment]
Now that nvaccess/nvda#10784 has been merged, NVDA has full support for Windows Terminal as of 2020.2! It also now supports the post #4018 Windows Console with UIA if "use UI Automation to access the Windows Console when available" is enabled from advanced settings. Builds from NVDA master are available [here](http://nvda-project.org/snapshots).

**Comment by carlos-zamora** [comment]
> Now that [nvaccess/nvda#10784](https://github.com/nvaccess/nvda/pull/10784) has been merged, NVDA has full support for Windows Terminal as of 2020.2! It also now supports the post #4018 Windows Console with UIA if "use UI Automation to access the Windows Console when available" is enabled from advanced settings. Builds from NVDA master are available [here](http://nvda-project.org/snapshots).

Thanks for all your hard work @codeofdusk! As we move forward with some internal testing, @cinnamon-msft and I will make sure NVDA v2020.2 is used. 😊
