### ISSUE TITLE
MEGATHREAD: Commandline Args Follow-Up Work

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#4632]
## Reference
* Original issue: #607
* [Original Spec](https://github.com/microsoft/terminal/blob/master/doc/specs/%23607%20-%20Commandline%20Arguments%20for%20the%20Windows%20Terminal.md) (Added in #3495)
* Initial Implementation PR: #4023
* [UsingCommandlineArguments.md](https://github.com/microsoft/terminal/blob/master/doc/user-docs/UsingCommandlineArguments.md)

## Untriaged Bugs/Features
* [ ] #4619 wt does not handle newlines properly 

## 1.0 Bugs
* [ ] #4618 wt command-line cannot consistently parse more than one argument 
* [ ] #4602 WT -? -help --help window should include a link to the command line arguments

## The Help Dialog
* [ ]  #4612 Help windows contain different help messages dependent of the way how help is triggered.
* [ ] The Help Dialog should have copy-pasteable text

## Post 1.0 features
* [ ] #4620 Add support for `initialPosition` and others
  - From the spec: 
  > When parsing a `new-tab` command, configure the `TerminalApp::AppLogic` to
  set some initial state about itself, to handle the `new-tab` arguments
  [`--initialPosition`, `--maximized`, `--initialRows`, `--initialCols`]. Only
  set this state for the first `new-tab` parsed. These settings will overwrite
  the corresponding global properties on launch.
* [ ] Add support for `open-settings`
* [ ] Add support for `list-profiles`
* [ ] Add support for `focus-pane`
* [ ] Add support for `--file,-f configuration_file` for reading a list of commands from a file
* [ ] Add support for a profile to launch multiple panes using `wt` commands
* [ ] Add support for running a set of `wt` commands on startup

## Discussion
* [ ] #4611 -H and -V parameters shouldn't be case-sensitive 
* [ ] #4570 `;` is an annoying separator character
* [ ] #4601 long form arguments (e.g. `--profile`) have poor discoverability

**Comment by DHowett-MSFT** [comment]
I've moved #4619, #4618 and and #4602 into the v1.0 milestone.

**Comment by Karl-WE** [comment]
for any new args please consider reading and support this feature request before it get's out of control / focus.
#4601

**Comment by WSLUser** [comment]
@zadjii-msft Please add https://github.com/microsoft/terminal/issues/5494 to the list to add `-v, --version` to the list of args. All other Windows apps (linux apps too, but different arg) allow viewing the version via CLI.

**Comment by Guiorgy** [comment]
> Windows commandline args are usually /fooBar but ours are --fooBar and that's weird

Is there an open discussion for this, or is this only internal for now?

**Comment by zadjii-msft** [comment]
@Guiorgy I don't think there's a current nogoing discussion, but there's mot really any chance that we'll change this, considering that 1.0 has already shipped with `--fooBar` args. 

As we discovered over in https://github.com/microsoft/terminal/issues/4601#issuecomment-590879396, it turns out that `/fooBar` style params will actually secretly work as well, but we're not officially documenting that in case CLI11 ever changes that out from underneath us.

**Comment by Guiorgy** [comment]
@zadjii-msft Oh wow, it does work! 😃
Anyways, glad to hear that `--` isn't going anywhere. Personally, I hope you *officially* support both at some point.

**Comment by rashil2000** [comment]
Sorry, I couldn't find any documentation, but are `--height` or `--width` options for launching new window planned/supported?

(Use case: a desktop shortcut for opening neovim in WT. I'd like that window to be larger than what I have normally set for the terminal in settings.json through the `initialRows` and `initialCols` options)

**Comment by honeylizard** [comment]
After opening a WLS profile (e.g. Ubuntu), is there anyway to pass Unix style commands?

Running `wt.exe new-tab -p Ubuntu cd /example/path` opens the tab, but the terminal shows the error 

`[error 0x80070002 when launching 'cd /example/path']`

All the examples I've found so far show how to run Windows commands after a new-tab call, but nothing on unix/linux commands...

**Comment by htcfreek** [comment]
> und so far show how to run Windows commands after a new-tab call, but nothing on unix/linux commands...

Same for me with PowerShell or other profiles. I opened the issue #16062 .
