### ISSUE TITLE
Scenario: Improved keyboard handling

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#4999]
The Terminal's keyboard input is fundamentally backed by VT sequences, which limits the range of keys that we can actually send relative to what the console was capable of. This megathread is tracking all the issues that might be related to this:

* [x] Some keybindings used by PSReadLine aren't getting through #879
* [x] Bug Report: Control+Space not sent to terminal emulator. #2865
* [x] Shift+Enter always submits, breaking PSReadline features [Windows.Terminal] #530 
* [x] Powershell: Ctrl-Alt-? does not work in Windows Terminal #3079
* [x] Bug: ctrl+break is not ctrl+c #1119
* [x] Something wrong with keyboard modifiers processing? #1694 
* [x] Numeric input not accepted by choice.exe #3608 
* [ ] Ctrl+Keys that can't be encoded as VT should still fall through as the unmodified character #3483
* [x] Modifier keys are not properly propagated to application hosted in Windows Terminal #4334 / #4446
* [ ] We may be able to fix the Ctrl+Backspace/Ctrl+H mixup that resulted in #5957.

Before 2.0, we're hoping on adding support for parsing a much broader variety of keys via conpty.

Keys that we definitely need to support, that don't have unique VT sequences:
* [x] <kbd>Ctrl+Space</kbd> (#879, #2865)
* [x] <kbd>Shift+Enter</kbd> (#530)
* [x] <kbd>Ctrl+Break</kbd> (#1119)
* [x] <kbd>Ctrl+Alt+?</kbd> (#3079)
* [x] <kbd>Ctrl</kbd>, <kbd>Alt</kbd>, <kbd>Shift</kbd>,  (without another keydown/up) (#3608, #4334, #4446)

**Comment by zadjii-msft** [comment]
_This is a work-in-progress_

Potential Solutions:

## `DECPCTERM`
[VT100.net doc](https://vt100.net/docs/vt510-rm/DECPCTERM.html)

#### Pros:
* Enables us to send key-down and key-up keys independently
* Enables us to send modifiers on their own
* Part of the VT 510 standard
#### Cons:
* neither `xterm` nor `gnome-terminal` (VTE) seem to implement this. I'm not sure if anyone's got a reference implementation for us to work with.
* Unsure how this would work with other keyboard layouts
	- [this doc](https://vt100.net/docs/vt510-rm/chapter8.html#S8.13) seems to list the key-down/up codes for all the en-us keyboard keys, but the scancodes for these are different for up and down. That would seem to imply we couldn't just shove the Win32 scancode in those bits 


## `xterm` "Set key modifier options"
Notably looking at [`modifyOtherKeys`](https://invisible-island.net/xterm/manpage/xterm.html#VT100-Widget-Resources:modifyOtherKeys).

#### Pros:
* `xterm` implements this so there's a reference implementation
* 
#### Cons:
* Only sends the sequence on key-up
* Doesn't send modifiers all on their own

## kitty extension
[Reference](https://sw.kovidgoyal.net/kitty/protocol-extensions.html#keyboard-handling)
TODO

## ConEmu `INPUT_RECORD` extension
TODO - does this even exist? IIRC this was the original plan like, years ago

## Things to keep in mind

* Would this encoding be mixable with other normal VT processing easily? 
  - How would the Terminal know when it should send a \<chosen_encoding> key vs a normally encoded one?
	- For ex, Ctrl+space - should we send NUL or \<chosen_encoding's version of ctrl+space>
* If there's a scenario where Windows Terminal might _not_ be connected to a conpty, then how does conpty enable \<chosen_encoding>?

**Comment by j4james** [comment]
Another option to consider is _Key Position Mode_ ([`DECKPM`](https://vt100.net/docs/vt510-rm/DECKPM.html)) which reports the state of the modifier keys along with each key press (see [`DECEKBD`](https://vt100.net/docs/vt510-rm/DECEKBD.html) for the actual report format). I don't think it has separate keyup and keydown events, but it does have an option to report modifier keypresses separately (see [`DECSMKR`](https://vt100.net/docs/vt510-rm/DECSMKR.html)).

> How would the Terminal know when it should send a <chosen_encoding> key vs a normally encoded one?

I assumed this is something the conpty host would initiate on startup, requesting whichever mode (or modes) we decided to support. If the terminal at the other end supported the requested mode, then it would start reporting keypresses in that format.

In some cases, if the key reporting sequences can mean different things in different modes, the host might need to know whether the client had actually accepted the request to use a particular mode. In the case of `DECKPM` you could determine that by querying the mode state with [`DECRQM`](https://vt100.net/docs/vt510-rm/DECRQM.html). In the case of `DECPCTERM`, you could determine whether the client supported the option from the [`DA1`](https://vt100.net/docs/vt510-rm/DA1.html) report.

**Comment by zadjii-msft** [comment]
Thanks for the suggestions @j4james. Those worry me the same way that DECPCTERM does in that there doesn't seem to be any terminal applications that I can use as a reference implementation for them 😕

**Comment by j4james** [comment]
> Those worry me the same way that `DECPCTERM` does in that there doesn't seem to be any terminal applications that I can use as a reference implementation for them

What about this? https://www.amazon.com/DEC-VT510-TERMINAL/dp/B016YJZYVK 😄 
I've actually considered getting one myself, although I don't really have the space for it.

Anyway I'd much prefer implementing an actual standard over any of the proprietary extensions, but I suspect we'll probably end up implementing several of the protocols anyway. I know I would want to add support for the DEC standards even if nobody else does, just because I'd like WT to be a proper terminal emulator. And we'll probably want to do XTerm's modifier extension, because I think there are existing apps that make use of it.

I don't really see the point of coming up with our own proprietary protocol, though, unless it can actually do something that `DECPCTERM` doesn't. You still don't have a reference implementation, and you've got the additional effort of inventing your own protocol.

> [this doc](https://vt100.net/docs/vt510-rm/chapter8.html#S8.13) seems to list the key-down/up codes for all the en-us keyboard keys, but the scancodes for these are different for up and down. That would seem to imply we couldn't just shove the Win32 scancode in those bits

I haven't really looked at it in much detail, but the impression I got was that the "make" code was a standard scancode, and the "break" code is just the same thing with the high bit set (for the two byte sequences, it'll be the second byte that has the high bit set).

**Comment by zadjii-msft** [comment]
> What about this? [amazon.com/DEC-VT510-TERMINAL/dp/B016YJZYVK](https://www.amazon.com/DEC-VT510-TERMINAL/dp/B016YJZYVK) 😄
> I've actually considered getting one myself, although I don't really have the space for it.

We can barely convince management to get us high-dpi displays, I doubt I could get that approved 😆 

>  I would want to add support for the DEC standards even if nobody else does, just because I'd like WT to be a proper terminal emulator

I totally agree with this sentiment. I don't disagree that this is a valuable goal to move towards. However, from where I'm sitting looking at these bugs, being a better _terminal_ emulator doesn't actually help us solve them. Being a better _console_ emulator would though. 

The way I'm looking at it now is that we can definitely make conhost a better terminal emulator independently of making the Windows Terminal a better console emulator. By letting the Terminal speak \<our INPUT_RECORD protocol> to conpty, then conpty can have real `INPUT_RECORD`s in it's input buffer that Win32 applications will be able to read just the way they like to. Then, conhost is also already good at taking `INPUT_RECORD`s and turning them into strings of characters for applications that request VT input. 

> You still don't have a reference implementation, and you've got the additional effort of inventing your own protocol.

Without a reference implementation, I'm kinda inventing my own protocol anyways though, right? 😉 I still hate this about this solution, but the crux of the issue is that there are going to be some legacy Win32 apps out there somewhere that are going to want some piece of information that will only come from an `INPUT_RECORD`, and only a Win32 solution will work for this. 


Maybe there's some future where the Terminal isn't connected to conpty. In that future, the Terminal will still be a better terminal emulator because it shares the same core terminal input translation as conhost does. So doing the `INPUT_RECORD` path isn't going to back the Terminal into a corner in the future.

**Comment by j4james** [comment]
> but the crux of the issue is that there are going to be some legacy Win32 apps out there somewhere that are going to want some piece of information that will only come from an INPUT_RECORD, and only a Win32 solution will work for this.

Maybe you're right. I was just hoping we'd have a solution where you could connect a standard terminal to the end of a conpty pipe and have it just work. With a proprietary solution that's never going to happen.

**Comment by zadjii-msft** [comment]
See but here's the thing I'm thinking - I think that's going to be just fine still. 

The way I'm imagining it right now, when conpty starts up, it's going to ask for some private input mode. As all good terminal emulators should, when they don't understand that sequence, they'll just ignore it. Then they'll send input like they currently do, and conpty will handle it just the same as it can currently. We'll translate the normal sequences the same way we currently do, and everything will work just as well as they currently do.

However, for something that's been updated to support win32-input-mode, like the Terminal, it'll see that private mode sequence and start sending the win32 compatible sequences instead. If other terminals wanted to also adopt this to work better _with legacy Windows applications_ they totally could, but I wouldn't say that this would be horribly important. 

Our guidance is still going to be "if you're authoring a commandline application, you should avoid these keyboard shortcuts or use VT input, otherwise your application might not work in all terminals". For things like Hyper, mintty, putty, they're still going to hit this bug unless they're updated. However, _regardless_ of which dialect we chose, they'd hit this bug, since none of them implement some reasonable alternative 😄 

I'm just thinking that a win32-specific solution to a win32-specific bug isn't the worst outcome. I do appreciate you keeping me honest though ☺️

**Comment by j4james** [comment]
> For things like Hyper, mintty, putty, they're still going to hit this bug unless they're updated. However, regardless of which dialect we chose, they'd hit this bug, since none of them implement some reasonable alternative

Yeah. If I'm being realistic, it really doesn't matter. But I can't help thinking how cool it would have been to hook up a DEC terminal, built nearly 30 years ago, and have it work near perfectly with modern console apps. I means that's essentially what the PCTerm mode was designed for in the first place.

Then you could tell any terminal emulators that want the same level of functionality they'd just need to implement an existing VT protocol. As feature requests go, I suspect that's a lot easier to justify to some people than a proprietary win32-specific protocol.

Anyway, I'm just musing here on what might have been. I do understand your reasons for going the other route.

**Comment by machekku** [comment]
Hi, I'm just a lurker and not an expert in this area, but when I saw this task I immediately thought of libtermkey/libtickit and their author who's been trying to improve terminal keyboard input for a long time: http://www.leonerd.org.uk/hacks/fixterms/ Maybe this could give you some ideas.

**Comment by zadjii-msft** [comment]
As of 6b2d95264

* [x] Some keybindings used by PSReadLine aren't getting through #879
  - [x] <kbd>Ctrl+Backspace</kbd> (`BackwardKillWord`)
    - ✔ already works in 1.0 
  - [x] <kbd>Shift+Ctrl+Enter</kbd> (`InsertLineBelow`)
    - 🎉 This is a new fix! 🎉
  - [x] <kbd>Ctrl+Space</kbd> (`MenuComplete`)
    - ✔ already works in 1.0 
  - [x] <kbd>Shift+Tab</kbd> (`TabCompletePrevious`)
    - ✔ already works in 1.0 
  - [x] <kbd>Alt+0</kbd> (`DigitArgument`) (and other digits)
    - ✔ already works in 1.0 
  - [ ] <kbd>PageDown</kbd> (`ScrollDisplayDown`)
    - ⚠ Not sure this is even possible with conpty at all, though this can be bound directly in the Terminal
  - [ ] <kbd>Ctrl+PageDown</kbd> (`ScrollDisplayDownLine`)
    - ⚠ Not sure this is even possible with conpty at all, though this can be bound directly in the Terminal
  - [ ] <kbd>PageUp</kbd> (`ScrollDisplayUp`)
    - ⚠ Not sure this is even possible with conpty at all, though this can be bound directly in the Terminal
  - [ ] <kbd>Ctrl+PageUp</kbd> (`ScrollDisplayUpLine`)
    - ⚠ Not sure this is even possible with conpty at all, though this can be bound directly in the Terminal
  - [x] <kbd>Ctrl+Alt+?</kbd> (`ShowKeyBindings`)
  - [x] <kbd>Alt+?</kbd> (`WhatIsKey`)
    - ✔ already works in 1.0 
* [x] Bug Report: Control+Space not sent to terminal emulator. #2865
    - ✔ already works in 1.0 
* [x] 🎉 Shift+Enter always submits, breaking PSReadline features [Windows.Terminal] #530 
* [x] 🎉 Powershell: Ctrl-Alt-? does not work in Windows Terminal #3079
* [ ] Bug: ctrl+break is not ctrl+c #1119
  - Pause/Break now works in this scenario to pause the ping output
  - ❌ Ctrl+C STOPPED working!
* [x] 🎉 Something wrong with keyboard modifiers processing? #1694 
* [x] 🎉 Numeric input not accepted by choice.exe #3608 
* [ ] Ctrl+Keys that can't be encoded as VT should still fall through as the unmodified character #3483
  - Okay this one's different. For this one, if a Ctrl+char hits the normal VT translation path, and that char is in (0x20,0x3f]|[0x60,0x7e], then we should just send that char
* [x] 🎉 Modifier keys are not properly propagated to application hosted in Windows Terminal #4334 / #4446

**Comment by tasogare3710** [comment]
I came from #5957.

I found other different key codes.

ctrl+J -> ^Q == LF -> DC1
ctrl+? -> ^_ == DEL -> US

**Comment by zadjii-msft** [comment]
With #6309 merged, I'm closing this issue out. #3483 and #5957 were both bugs that can be solved on their own, and weren't really a part of this scenario.

**Comment by unxed** [comment]
To simplify implementation of win32-input-mode in terminals on platforms other than Windows, I wrote a small library that translates X11/Wayland XKB key syms into Windows key codes. There is also a demo application that prints win32-input-mode escape sequences based on X11 input events. I hope this will help those who want to add support for the win32-input-mode to their terminals designed for platforms other than Windows.

https://github.com/unxed/xkb2win

**Comment by determin1st** [comment]
eee... mm.. so where's the protocol description? how do i parse it without any description

**Comment by zadjii-msft** [comment]
Here's the spec: https://github.com/microsoft/terminal/blob/main/doc/specs/%234999%20-%20Improved%20keyboard%20handling%20in%20Conpty.md

**Comment by determin1st** [comment]
notes
- it's not INPUT_RECORD, its KEY_RECORD, INPUT_RECORD includes MOUSE_RECORD and others
- same negligence for parsers as in kitty's design. querying must come first. what will happen with `9001$p` ?
- who needs scancodes?
- repeat and keyup / keydown may be transferred as a single value
- char codepoint may be the length of utf8 bytes that follow

here's my recent take on this topic ... (im really lost in these github interfaces with thousands of links etc, no centralized chat or somehting.. so lost it)

i think one more possible scenario will be moving from `ReadConsoleInput` to generic `ReadFile` bytes like in *nix systems..

**Comment by unxed** [comment]
FYI: kitty protocol escape sequences generation from Windows compatible Key Event Record, public domain.

https://github.com/microsoft/terminal/issues/11509#issuecomment-2308421220
