### ISSUE TITLE
RELEASE: v1.0 Release Checklist

### ISSUE THREAD

**Issue by cinnamon-msft** [microsoft/terminal#5813]
Here's the current working checklist of things we need to complete on the day of release. Please add to this as you think of things!

- [x] Update aka.ms links
- [x] Update README
- [x] Bump version number in app and PDP
- [x] Produce final build with new version number (@DHowett-MSFT)
- [x] Prep PDPs to launch for the day of
- [x] Publish 1.0 blog (@cinnamon-msft)
- [x] Submit manifest change
- [ ] CELEBRATE! 🎉

**Comment by DHowett** [comment]
Now all that's left to do is Celebrate, I think?

**Comment by mkitzan** [comment]
Just saw [news](https://devblogs.microsoft.com/commandline/windows-terminal-1-0/), huge congrats on 1.0! 🎉

**Comment by DHowett** [comment]
Thank you :)

**Comment by DarthJahus** [comment]
`[x] Celebrate`
