### ISSUE TITLE
Scenario: TerminalControl Interactivity Improvements

### ISSUE THREAD

**Issue by carlos-zamora** [microsoft/terminal#6106]
This is a comprehensive list of improvements to our interactivity model for v2. This is not finalized and may be updated as new issues come in or we make cuts for v2.

## (Hidden) Refactors
- [ ] #5099: mouse selection should begin/end at nearest cell boundary
- [ ] #5814: Use til::point
- [ ] #3538: GenRTF() and GenHTML() should use shared components
- [ ] #4423: Refactor Word Expansion (shared between accessibility/selection)

### Features
- [ ] #4557: Shift+Multi-Click selection expansion
- [ ] #3884: persistent selection on copy
- [ ] Word Selection Improvements
   - [ ] #3077: Unicode character categories
   - [ ] #3077: regex support
- [ ] #4993: Scenario: Keyboard Selection
   - refer to the GitHub issue above for more details
- [ ] Copy Formatted Text
   - #4191: add array support
   - #5262: add keybinding arg

### Bugs
- [ ] #5626: start selection from padding
- [ ] #5766: Shift+Click initial click doesn't work

### Features
- [ ] #3149: Touch Zoom
- [ ] #3109: Inertial Scrolling
- [ ] #5159: Touch Selection

## Miscellaneous Major Features
- [ ] SnapOnOutput:
   - [ ] #980: pause scrolling when a selection exists
   - [ ] #3863: pause scrolling when not at bottom
      - [ ] also add a keybinding for that (ScrollLock)
- [ ] #1553: Pointer Bindings

**Comment by DHowett** [comment]
If we do #6842 before we do #5099, #5814 and #4993 WPF gets it for free. Otherwise we need to disentangle those three when we _do_ start 6842.
