### ISSUE TITLE
[Scenario] Retro Terminal Effect Improvements

### ISSUE THREAD

**Issue by ianhan** [microsoft/terminal#6191]
So, the glow effect is neat, but that is not what a CRT looks like. CRTs were not blurry. It looks more like a composite TV effect, and it's hard to use.

Check out this terminal and the effects it has - they are clearly a labor of love. Can we do something like that?
https://github.com/Swordfish90/cool-retro-term

![image](https://user-images.githubusercontent.com/6833412/82842997-d7258780-9e98-11ea-8615-d706cdac1bc9.png)

![image](https://user-images.githubusercontent.com/6833412/82843002-df7dc280-9e98-11ea-8a4b-9569d4b89a6d.png)

Thanks!

**Comment by zadjii-msft** [comment]
I mean, we're happy to accept more contributions in this area 😉 The retro effect was wholly a community contribution. At some point in the future, we'll probably move it to being an extension (#4000), but for now, it lives in this codebase, and we'd be happy to accept more improvements to it.

This is now the "retro terminal effects improvements" megathread.


### Additional settings
* [ ] Add setting to retro terminal shader to control blur radius, color #3930
* [ ] Add setting to retro terminal shader to enable drawing scanlines #3929 
* [ ] Add a shortcut action for toggling retro terminal effects #5402

### Bugs
* [ ] Retro effect not working on certain/older systems #4229

**Comment by ianhan** [comment]
Thank you for considering!

**Comment by zadjii-msft** [comment]
For folks following this thread: In Terminal 1.6 we've added support for "custom pixel shaders". This will let you do way more than just what the basic retro terminal effect does. I'm not a shader expert, so I don't know how to make something that looks like OP, but I'm sure it's possible somehow. The original PR had something that looked similar to OP in the "[Retro II](https://github.com/microsoft/terminal/pull/7058/files#diff-d3ed932e450b5babb960131e8d75fcf72adfa379c2789cdaa37bf7e3636afb24)" shader.

Feel free to play around with that to see if you can't find something good, and share the results!

**Comment by zadjii-msft** [comment]
Hey I'm gonna close this out now that #8565 and #8935 have landed. The custom pixel shaders will let you do this (and more), so I'm not sure there's a reason to leave this issue open any longer. Thanks!

P.S. If someone manages to whip up a shader that looks like OP (and you have the rights to contribute it), I'd _love_ to throw it in the shader samples!
