### ISSUE TITLE
Megathread: Sometimes, focus moves weirdly

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#6680]
I'm just making a megathread for all the issues we've got so far, because there's a bunch, and I'm getting the feeling there needs to be some other comprehensive solution.

* [ ] Clicking the current tab to raise the window should focus the text area #3609
* [ ] ESC from the Tab ContextMenu should return focus to the Terminal #5750
* [x] Launching "Find" from Command Palette doesn't focus the search box #6662
  - Unsure when exactly this was fixed
* [x] Focus bug 1
   - open command palette
   - press shift+tab
   - your focus is now in the ~~underlying terminal~~ 
     - ~~As of 1.7, now the focus is _gone from the world_?~~
       - As of at least 1.9, this takes focus to the command list.
* [x] Focus bug 2
   - open command palette
   - type in `asdf`, or anything that causes no results to match.
   - press tab
   - your focus is now [_gone from this world_](https://thedarkestfallingstar.files.wordpress.com/2019/03/tumblr_mhv1cxlzim1s3uvpwo6_500.gif?w=354)
   - Unsure when exactly this was fixed
* [x] The "Rename tab" action removes focus from terminal #9160 (PR: #9162)

if we don't manually yeet the focus back into the active control, then pressing <kbd>esc</kbd> to close the command palette actually ends up with focus in the first Tab, similar to in #5750.

I do have one open PR: "When the tab receives focus, immediately move focus to the active control #6290", but I have no idea if that's the right solution. It doesn't feel like it is.
