### ISSUE TITLE
Migrate static sleet feed into public Azure DevOps artifact feed

### ISSUE THREAD

**Issue by miniksa** [microsoft/terminal#6952]
Per @jevansaks, Azure DevOps apparently made artifact feeds a thing that can be made public (and not just "authenticated users.")

The only reason we were using a Sleet feed in an Azure Blob Storage bucket for our NuGet packages was because of this limitation.

This work item represents decommissioning future use of the sleet feed in the bucket, creating one of those public artifact feeds on the `ms` instance of Azure DevOps that we already use for build, and publishing our dependent artifact pages there.

This is what we think needs to move:
- [x] Microsoft.UI.XAML package 
- [x] vcpkg for cpprestsdk
- [x] vcpkg for telnetpp
- [x] Terminal theme helpers

I also expect this to help us enable doing PGO the same way that https://github.com/microsoft/microsoft-ui-xaml does from @bartekk8's work on that there.

**Comment by jevansaks** [comment]
[Here's where they made it a thing](https://devblogs.microsoft.com/devops/new-with-azure-artifacts-public-and-project-scoped-feeds/).
