### ISSUE TITLE
Feature: Application State

### ISSUE THREAD

**Issue by DHowett** [microsoft/terminal#8324]
Terminal is going to need a place to store application "state", including:
* [ ] Dialogs the user has chosen to hide with a `[ ] Do not ask again` checkbox, as proposed in #6641
* [x] Which dynamic profiles have been generated, as a way to resolve user dissatisfaction (#3231) around profiles "coming back"
* [x] On-screen position of the window, active session state, layout, etc. for eventual restoration (#766, not #961)
* [x] #10798 Add info about the `exit code` message the first time it happens.
* [x] #11026

**Comment by zadjii-msft** [comment]
@DHowett I have half a mind to close this out since 4/5 of the original ideas are all added now. This issue feels like it was tracking just "add the infrastructure to do this". Do you think we need to leave this open to track follow ups (like other megathreads)?

**Comment by DHowett** [comment]
Nah, let's kill it.
