### ISSUE TITLE
The LocalTests are broken, March 2021 edition

### ISSUE THREAD

**Issue by zadjii-msft** [microsoft/terminal#9659]
Oh, no, they were broken even before this. Welp. looks like I'll be fruitlessly trying to bisect that today.

* [x] ❌ cf5dc28 (before #9656)
* [x] ✔️ 690fbbb (before defterm)
* [x] ❌ 906edf7002b8ccf4d819fcc6f45a68f7815b3252 (defterm)

It was definitely defterm

_Originally posted by @zadjii-msft in https://github.com/microsoft/terminal/pull/9656#issuecomment-810353258_
